services:
  api:
    image: norttis/studiostudio-server:latest
    container_name: studiostudio_api
    env_file:
      - .env.docker
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
    depends_on:
      - postgres
    networks:
      - studiostudio_net

  postgres:
    image: postgres:17
    container_name: studiostudio_postgres
    env_file:
      - .env.docker
    restart: unless-stopped
    environment:
      POSTGRES_DB: study_studio
      POSTGRES_USER: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - studiostudio_net

volumes:
  postgres_data:

networks:
  studiostudio_net:
    driver: bridge
